config/routes.rb
Rails.application.routes.draw do

  get 'login/edit' => 'logins#edit', as: 'login_edit'
  patch 'login/edit' => 'logins#update'
  post 'login/edit' => 'logins#update'

  get 'board/index' => 'boards#index'
  post 'board/index' => 'boards#create'
  delete 'board/:id' => 'boards#destroy'
  get 'board/:id/show' => 'boards#show', as: 'board_show'
  get 'board/:id/edit' => 'boards#edit', as: 'board_edit'
  post 'board/:id/edit' => 'boards#update'

  get 'board/:id/comment' => 'board_comments#index', as: 'board_comment' 
  post 'board/:id/comment' => 'board_comments#create'

  resources :members do
    get "search", on: :collection
  end

  get '/login' => 'sessions#index', as: 'login_index'
  post '/login' => 'sessions#login' 
  delete '/login' => 'sessions#destroy'
  get 'login/new' => 'sessions#new', as: 'login_new'
  post 'login/new' => 'sessions#create'

  root "sessions#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
end

app/models/boardcomment.rb
class Boardcomment < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  has_secure_password

  attr_accessor :current_password
  validates :password, presence: {if: :current_password}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :login_required

  private def current_member
    User.find_by(id: session[:member_id]) if session[:member_id]
  end

  class LoginRequired < StandardError; end
  class Forbidden < StandardError; end

  private def login_required
    begin
      raise LoginRequired unless current_member
    rescue
      flash.alert = "ログインしてください。"
      redirect_to :root
      return
    end
  end
end

app/controllers/board_comments_controller.rb
class BoardCommentsController < ApplicationController
  
  def index
    query = "SELECT row_id, id, comment, created_at FROM boardcomments WHERE board_id=? ORDER created_at;"
    @board = Board.find(params[:id])
    @comments = Boardcomment.where(board_id: params[:id]).order(created_at: :asc)
    @comment = Boardcomment.new
  end

  def create
    @comment = Boardcomment.new(params[:form_comment])
    @comment.board_id = params[:id]
    @comment.commentator = session[:name]

    @comments_count = Boardcomment.where(board_id: params[:id] ).count
    

    # 登録済みコメントが1000コメント以上の場合
    begin
      if @comments_count >= 1000
        raise "コメントが1000コメントを超えました"
      end
    rescue  Exception
      flash.alert = "コメントが1000コメントを超えました。新しい掲示板を作成してください。
      "
      redirect_to board_comment_url
      return
    end
    
    # 登録済みコメントが1000コメント未満の場合
    if @comment.save
      redirect_to board_comment_url, notice: "コメントを送信しました。"
      return
    else
      render "board_comment"
      return
    end
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @boards = Board.all
    @board = Board.new
  end

  def create
    @board = Board.new(params[:board])
    @board.creator_name = session[:name]

    if @board.save 
      redirect_to board_index_url, notice: "掲示板を作成しました。"
    else
      render "board"
    end
  end

  def show
    @board = Board.find(params[:id])
  end

  def edit
    @board = Board.find(params[:id])
  end

  def update
    @board = Board.find(params[:id])
    @board.board_name = params[:board_form][:board_name]

    if @board.save
      redirect_to board_show_url, notice: "掲示板名を更新しました。"
    else
      render 'board/:id/edit'
    end
  end

  def destroy
    board = Board.find(params[:id])
    board.destroy
    redirect_to board_index_url, notice: "掲示板を削除しました。"
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController

  def edit
    @user = User.find(session[:member_id])
  end

  def update
    @user = User.find(session[:member_id])
    current_password = params[:user][:current_password]
    
    if current_password.present?
      if @user.authenticate(current_password)
        @user.assign_attributes(params[:user])
        if @user.save
          redirect_to board_index_url, notice: "パスワードを変更しました。"
        else
          render 'logins/edit'
        end
      else
        render 'logins/edit'
      end
    else
      render 'logins/edit'
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required

  def index
    @user = User.new
  end

  def login
    member = User.find_by(name: params[:name])
    if member&.authenticate(params[:password])
      session[:member_id] = member.id
      session[:name] = params[:name]

      redirect_to board_index_path, notice:"ログインしました。"
    else
      flash.alert = "名前とパスワードが一致しません。"
      render 'sessions/index'
    end
  end

  def destroy
    session.delete(:member_id)
    session.delete(:name)
    redirect_to :root
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      redirect_to login_index_url, notice: "ユーザを登録しました。"
    else
      render 'sessions/new'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_comments_helper.rb
module BoardCommentsHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/board_comments/index.html.erb
<% i=1 %>
<header>
  <div class="header-item">
    <%= image_tag "site_title_image.jpg", alt: "タイトル画像", id: 'title_image', class: "title_image" %>
    <ul>
      <li><%= link_to 'ログアウト', :login, method: :delete, data: {confirm: "ログアウトしてもよろしいですか？"} %></li>
      <li><%= link_to '掲示板一覧', board_index_path %></li>
    </ul>
  </div>
</header>
<main>
  <div class="container">
    <div class="create_comment_menu">
      <%= form_for :form_comment do |form| %>
        <div class="new_comment">
          コメント:<%= form.text_field :comment, size: 100, maxlength: 60 %>
          <%= form.submit "コメント送信" %>
        </div>
      <% end %>
    </div>
    <% if flash.alert %>
      <div class="alert-area">
        <p class="alert">
          <%= flash.alert %>
        </p>
      </div>
    <% end %>
    <div class="main-comment-box">
      <div class="board_name">
        <h2>掲示板名：<%= @board.board_name %></h2>
      </div>
      <table>
        <tr>
          <th style="text-align:left; width:50px;">番号</th>
          <th style="text-align:left; width:100px">送信者</th>
          <th style="text-align:left">コメント</th>
          <th style="width:150px;">送信日時</th>
        </tr>
        <% @comments.each do |comment| %> 
        <tr>
          <td style="width:50px;"><%= i %></td>
          <td style="width:100px"><%= comment.commentator %></td>
          <td><%= comment.comment %></td>
          <td style="text-align:center;width:150px;"><%= comment.created_at.strftime('%Y/%m/%d %H:%M') %></td>
        </tr>
        <% i += 1 %>
        <% end %>
      </table>
    </div>
  </div>
</main>
<footer>
</footer>

app/views/boards/edit.html.erb
<header>
  <div class="header-item">
    <%= image_tag "site_title_image.jpg", alt: "タイトル画像", id: 'title_image', class: "title_image" %>
    <ul>
      <li><%= link_to 'ログアウト', :login, method: :delete, data: {confirm: "ログアウトしてもよろしいですか？"} %></li>
      <li><%= link_to '掲示板一覧', board_index_path %></li>
    </ul>
  </div>
</header>
<main>
  <div class="container">
    <div class="board_info">
      <%= form_for :board_form do |form|%>
        掲示板番号：<%= @board.id%><br>
        掲示板名　：<%= form.text_field :board_name, size:60, maxlength:60 %><br>
        作成日時　：<%= @board.created_at.strftime("%Y-%m-%d %H:%M") %><br>
        <%= form.submit "変更する" %>
      <% end %>
      <%= link_to '掲示板詳細に戻る', board_show_path %>
    </div>
  </div>
</main>
<footer>
</footer>

app/views/boards/index.html.erb
<% genre=['マンガ','アニメ','ドラマ','映画','雑談','その他' ] %>
<header>
  <div class="header-item">
    <%= image_tag "site_title_image.jpg", alt: "タイトル画像", id: 'title_image', class: "title_image" %>
    <ul>
      <li><%= link_to 'ログアウト', :login, method: :delete, data: {confirm: "ログアウトしてもよろしいですか？"} %></li>
      <li><%= link_to '掲示板一覧', board_index_path %></li>
      <li><%= link_to 'パスワード変更', login_edit_path %></li>
    </ul>
  </div>
</header>
<main>
  <div class="container">
    <div class="create_board_menu">
      <%= form_for :board do |form| %>
        <div class="new_genre">
          ジャンル:<%= form.select :genre, genre %>
        </div>
        <div class="new_boardname">
          掲示板名:<%= form.text_field :board_name, size: 70, maxlength: 30 %>
          <%= form.submit "掲示板新規作成" %>
        </div>
      <% end %>
    </div>
    <div class="main-box">
      <table>
        <tr>
          <th style="text-align:left; width:100px;">ジャンル</th>
          <th style="text-align:left;">作成者</th>
          <th style="text-align:left">掲示板名</th>
          <th style="width:150px;">作成日</th>
          <th style="width:100px; text-align:left;"></th>
        </tr>
        <% @boards.each do |board| %> 
        <tr>
          <td style="width:100px;"><%= board.genre %></td>
          <td style="width:120px;"><%= board.creator_name%></td>
          <td><%= link_to board.board_name, "#{board.id}/comment" %></td>
          <td style="text-align:center;width:150px;"><%= board.created_at.strftime('%Y/%m/%d') %></td>
          <td><%= link_to '詳細', "#{board.id}/show" if board.creator_name == session[:name] %>|<%= link_to '削除', "#{board.id}", method: :delete, data: {confirm: "掲示板#{board.board_name}を削除します。よろしいですか？" } if board.creator_name == session[:name] %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</main>
<footer>
</footer>

app/views/boards/show.html.erb
<% genre=['マンガ','アニメ','ドラマ','映画','雑談','その他' ] %>
<header>
  <div class="header-item">
    <%= image_tag "site_title_image.jpg", alt: "タイトル画像", id: 'title_image', class: "title_image" %>
    <ul>
      <li><%= link_to 'ログアウト', :login, method: :delete, data: {confirm: "ログアウトしてもよろしいですか？"} %></li>
      <li><%= link_to '掲示板一覧', board_index_path %></li>
    </ul>
  </div>
</header>
<main>
  <div class="container">
    <div class="board_info">
      掲示板番号：<%= @board.id%><br>
      掲示板名　：<%= @board.board_name %><br>
      作成日時　：<%= @board.created_at.strftime("%Y-%m-%d %H:%M") %><br>
      <%= link_to '編集', board_edit_path %>|<%= link_to '削除', "/board/#{@board.id}", method: :delete, data: {confirm: "掲示板#{@board.board_name}を削除します。よろしいですか？"} %><br>
      <%= link_to '掲示板一覧に戻る', board_index_path %>
    </div>
  </div>
</main>
<footer>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Keijibang</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="notice">
      <%  if flash.notice %>
        <p class="notice"><%= flash.notice %></p>
      <% end %>
    </div>
    
    <%= yield %>
  </body>
</html>

app/views/logins/edit.html.erb
<header>
  <div class="header-item">
    <%= image_tag "site_title_image.jpg", alt: "タイトル画像", id: 'title_image', class: "title_image" %>
  </div>
</header>

<main>
  <div class="container">
    <div class="login_main_box">
      <div class="new_user_menu">
        <h2>パスワード変更</h2>
        <%= form_for @user,:url => {:action => :update} do |form| %> 
          <%= form.label :current_password, "現在のパスワード" %><br>
          <%= form.password_field :current_password, sizre: 50, maxlength: 50 %></br><br>          
          <%= form.label :password, "新しいパスワード" %><br>
          <%= form.password_field :password, size: 50 %><br><br>
          <%= form.label :password2, "新しいパスワード(確認)" %><br>
          <%= form.password_field :password_confirmation, size: 50 %><br><br>
          <%= form.submit "パスワード変更" %><br><br>
          <%= link_to "掲示板一覧に戻る",  board_index_path %>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/logins/index.html.erb
<header>
  <div class="header-item">
    <%= image_tag "site_title_image.jpg", alt: "タイトル画像", id: 'title_image', class: "title_image" %>
  </div>
</header>

<main>
  <div class="container">
    <div class="login_main_box">
      <div class="login_menu">
        <h2>ログイン</h2>
        <% if flash.alert %>
          <p class="alert">
            <%= flash.alert %>
          </p>
        <% end %>
        <%= form_tag :session, id: "login_form" do %>
          <label>ユーザー名:</label><br>
          <input type="text" name="name" size="50"></br><br>
          <label>パスワード:</label><br>
          <input type="password", name="password" size="50"><br><br>
          <input type="submit" value="ログイン"><br><br>
          <%= link_to "新規ユーザ登録", login_new_path %>
        <% end %>
      </div>
    </div> 
  </div>
</main>